listener 1883 0.0.0.0
allow_anonymous false

# EDIT these paths to match your installation
acl_file C:\<monorepo_root>\config\mqtt\aclfile.txt # replace <monorepo_root> with the actual path to the root of the monorepo
password_file C:\Program Files\Mosquitto\passwd # generate a passwd file with the README instructions, and place it here

# Optional: logging
persistence true
persistence_location C:\Program Files\Mosquitto\data\ # need to create this directory
log_type all
